<?php
// LOCATION: database/migrations/2026_08_24_100001_create_tasks_table.php
//
// Re-architected task model: ONE task = ONE admin-provided code, shared by
// however many investors the admin assigns it to (1, 3, 100 — admin's
// choice). Per-investor tracking lives in task_assignments (next migration).
//
// This is additive only — the earlier investor_tasks/investor_task_logs
// tables from the original 1-code-per-investor design are left in place,
// untouched, and unused. Nothing is dropped or altered.

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('shared_tasks', function (Blueprint $table) {
            $table->id();

            // Admin-provided code (NOT system-generated by default — admin
            // types the exact code they want to hand out).
            $table->string('task_code')->unique();
            $table->foreignId('task_type_id')->constrained('task_types');

            $table->string('title');
            $table->text('description')->nullable();
            $table->text('requirements')->nullable();
            $table->decimal('required_amount', 15, 2)->nullable();

            // Task-level status governs whether the CODE is usable at all —
            // distinct from each investor's own progress (that's on
            // task_assignments). draft | active | expired | cancelled | closed
            $table->string('status')->default('active');

            // Shared activation/expiry window — applies to every investor
            // assigned to this task (Guide: "admin defines the task's
            // activation time, duration, and expiry").
            $table->timestamp('activates_at')->nullable();
            $table->timestamp('expires_at')->nullable();
            $table->timestamp('last_window_update')->nullable();
            $table->foreignId('window_modified_by')->nullable()->constrained('users')->nullOnDelete();
            $table->string('window_modified_reason')->nullable();

            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->timestamp('closed_at')->nullable();

            $table->softDeletes();
            $table->timestamps();

            $table->index('status');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('shared_tasks');
    }
};
